########################################################
# Hoodie Shop Frontend Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  name: hoodie-frontend
  labels:
    role: ui
    tier: frontend
    groupId: hoodie-shop
spec:
  selector:
    name: hoodie-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoodie-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-frontend
  template:
    metadata:
      labels:
        name: hoodie-frontend
    spec:
      containers:
        - name: hoodie-frontend
          image: hoodie-frontend:1.0
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://hoodie-backend-native:8082
---
########################################################
# Hoodie Shop Backend Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  name: hoodie-backend-native
  labels:
    role: rest-api
    tier: backend
    groupId: hoodie-shop
spec:
  selector:
    name: hoodie-backend-native
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoodie-backend-native-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-backend-native
  template:
    metadata:
      labels:
        name: hoodie-backend-native
    spec:
      containers:
        - name: hoodie-backend-native
          image: hoodie-bck-native:1.0
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: DB_HOST
              value: hoodie-db
            - name: DB_PORT
              value: "3306"
---
########################################################
# Hoodie Shop Database Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  name: hoodie-db
  labels:
    role: data-storage
    tier: database
    groupId: hoodie-shop
spec:
  selector:
    name: hoodie-db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hoodie-db
    groupId: hoodie-shop
  name: hoodie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-db
  template:
    metadata:
      labels:
        name: hoodie-db
        groupId: hoodie-shop
    spec:
      containers:
        - image: hoodie-db:1.0
          name: hoodie-db
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: mypass
            - name: MARIADB_USER
              value: catalogue_user
            - name: MARIADB_PASSWORD
              value: catalogue_pass
            - name: MARIADB_DATABASE
              value: hoodiedb
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 20
---