= Backend app

This is a simple Spring Boot REST app, running on port 8081.

== Build

In this directory run:

[source,shell script]
----
mvn
#or with Maven Daemon-- default goals: `clean install`
mvnd
----

== Run Locally

*Option 1:* Run from the source. Run the link:src/main/java/hoodie/shop/catalogue/CatalogueApplication.java[CatalogueApplication] class.

*Option 2:* Run from the jar. In the target directory run:

[source,shell script]
----
java -jar catalogue-1.0.jar
----
Note: For Windows runs you might need to use `127.0.0.1` instead of the actual IP the Database container is listening on.

If you want to point your backend to a database at a remote location run with:

[source,shell script]
----
java -jar target/catalogue-backend.jar --DB=<domain:port>
----

If the DB argument is not provided, the database location defaults to `localhost:3306`

== Build the Docker image

In this directory run:

[source]
----
docker build -t hoodie-backend:1.0 .
----

== Start the Container

Run wherever:

[source]
----
docker run -e DB=172.17.0.2:3306 --name local-hoodie-backend -d -p 8082:8082 hoodie-backend:1.0
----

Replace the value of the `DB` value with the IP:PORT where the database is available.

== Inspect IPAddress

The IPAddress is to be provided as an environment variable to the frontend container.

[source]
----
docker inspect local-hoodie-backend | grep IPAddress
----