= Setting up AWS environment

To run the Hoodie Shop in AWS we need to upload the Docker images in an AWS ECR and to deploy in a AWS EKS cluster.

== Push Docker Images to AWS ECR

*Note:* Build version 1.1 for AMD64 platform. This is necessary if you use a M1 silicone chip macOS for development, for certain images. For example the node image, that requires to be built for the right architecture otherwise the frontend does not start.

[source]
----
# login into ECR
aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com

# create repositories
aws ecr create-repository --repository-name hoodie-db --image-scanning-configuration scanOnPush=true --region eu-west-2
aws ecr create-repository --repository-name hoodie-backend --image-scanning-configuration scanOnPush=true --region eu-west-2
aws ecr create-repository --repository-name hoodie-frontend --image-scanning-configuration scanOnPush=true --region eu-west-2

# create and push images for M1 - version 1.0
# -- database --
cd database/docker-build
docker build -t hoodie-db:1.0 .
docker tag hoodie-db:1.0 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-db:1:0
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-db:1.0
# -- backend --
cd ../../backend-native
mvn spring-boot:build-image -Dspring-boot.build-image.imageName=hoodie-backend:1.0
docker tag hoodie-backend:1.0 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-backend:1.0
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-backend:1.0
# -- frontend --
cd ../frontend
docker build -t hoodie-frontend:1.0 .
docker tag hoodie-frontend:1.0 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-frontend:1.0
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-frontend:1.0

# create images for linux/amd64
# -- database --
export DOCKER_DEFAULT_PLATFORM=linux/amd64
cd database/docker-build
docker build -t hoodie-db:1.1 .
docker tag hoodie-db:1.1 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-db:1:1
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-db:1.1
# -- backend --
cd ../../backend-native
mvn spring-boot:build-image -Dspring-boot.build-image.imageName=hoodie-backend:1.1
docker tag hoodie-backend:1.1 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-backend:1.1
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-backend:1.1
# -- frontend --
cd ../frontend
docker build -t hoodie-frontend:1.1 .
docker tag hoodie-frontend:1.1 ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-frontend:1.1
docker push ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/hoodie-frontend:1.1
----

== Create the EKS Cluster

Reference: https://learnk8s.io/terraform-eks[https://learnk8s.io/terraform-eks]

Use the `aws` and `eksctl` CLIs to set it up. https://eksctl.io[Eksctl] is a convenient command-line tool to create an EKS cluster with a few simple commands. `eksctl` is an `aws eks` on steroids.

[source]
-----
# create the cluster
eksctl create cluster --name java-cro-cluster
# or
eksctl create cluster -f java-cro-cluster.yaml

# list the clusters in the current region
aws eks list-clusters

# ----- and at the end ...
# delete the cluster
eksctl delete cluster --name java-cro-cluster
-----

Import configuration into local `kubectl`

[source]
----
aws eks --profile default --region eu-west-2 update-kubeconfig --name java-cro-cluster

#check that it was added
kubectl cluster-info
kubectl cluster-info dump
kubectl get nodes  # expect 2 nodes

# show cluster nodes and their IPs (both should have external IPs)
kubectl get nodes -o wide |  awk {'print $1" " $2 " " $7'} | column -t


# get all contexts
kubectl config get-contexts

#  change to EKS context
kubectl config use-context arn:aws:eks:eu-west-2:${AWS_ACCOUNT}:cluster/java-cro-cluster
----

Install the dashboard. Reference: https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html
[source]
----
kubectl apply -f ../dashboard-deployment.yaml

# Create an eks-admin service account and cluster role binding
kubectl apply -f eks-admin-service-account.yaml
----

Retrieve an authentication token for the eks-admin service account.

[source]
----
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep eks-admin | awk '{print $1}')
----

To access the dashboard endpoint, open the following link with a web browser: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#!/login[here]

== Deploy Hoodie Shop

Create the namespace:

[source]
----
kubectl create namespace java-cro
----

Deploy the demo using the `aws-java-cro-verbose.yaml` file.

Check database is working, get the load balancer address to access it:

[source]
----
export DB_HOST=$(kubectl get service/hoodie-db --namespace=java-cro |  awk {'print $1" " $2 " " $4 " " $5'} | column -t)
----

Check connection on: `${DB_HOST}:3306`

== Clean up

If you need to delete images from AWS ECR
[source]
----
aws ecr batch-delete-image --repository-name ${REPO_NAME} --image-ids imageTag=1.0 --region eu-west-2
----
