########################################################
# Hoodie Shop Backend Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  namespace: hoodie-shop
  name: hoodie-backend
  labels:
    role: hoodie-backend-service
spec:
  selector:
    name: hoodie-backend
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hoodie-shop
  name: hoodie-backend
  labels:
    role: hoodie-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-backend
  template:
    metadata:
      labels:
        name: hoodie-backend
    spec:
      containers:
        - name: hoodie-backend
          image: hoodie-backend:1.0
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: DB_HOST
              value: hoodie-db
            - name: DB_PORT
              value: "3306"
---
########################################################
# Hoodie Shop Database Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  name: hoodie-db
  labels:
    role: hoodie-db-service
spec:
  selector:
    name: hoodie-db
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hoodie-shop
  labels:
    role: hoodie-db-deployment
  name: hoodie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-db
  template:
    metadata:
      labels:
        name: hoodie-db
    spec:
      containers:
        - image: hoodie-db:1.0
          name: hoodie-db
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: mypass
            - name: MARIADB_USER
              value: catalogue_user
            - name: MARIADB_PASSWORD
              value: catalogue_pass
            - name: MARIADB_DATABASE
              value: hoodiedb
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 20
---
