########################################################
# Hoodie Shop Frontend Service & Deployment
#######################################################
apiVersion: v1
kind: Service
metadata:
  namespace: java-cro
  name: hoodie-frontend
  labels:
    role: hoodie-frontend-service
spec:
  selector:
    name: hoodie-frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: java-cro
  name: hoodie-frontend
  labels:
    role: hoodie-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hoodie-frontend
  template:
    metadata:
      labels:
        name: hoodie-frontend
    spec:
      containers:
        - name: hoodie-frontend
          image: hoodie-frontend:1.0
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://localhost:32642
          livenessProbe:
            httpGet:
              path: /catalog
              port: 3000
            failureThreshold: 1
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /catalog
              port: 3000
            failureThreshold: 1
            periodSeconds: 1
---
